IF NOT EXISTS(SELECT ID FROM SYSOBJECTS WHERE NAME='TB_UNIDADE_MEDIDA') 
	CREATE TABLE [DBO].[TB_UNIDADE_MEDIDA]
	(
		[CD_UNIDADE]		[INT]	IDENTITY(1,1)	NOT NULL,
		[DS_UNIDADE]		[VARCHAR] (20)			NOT NULL,
		
		CONSTRAINT [PK_TB_UNIDADE_MEDIDA] PRIMARY KEY CLUSTERED ([CD_UNIDADE]) ON [PRIMARY]

	) ON [PRIMARY]
GO

IF NOT EXISTS(SELECT ID FROM SYSOBJECTS WHERE NAME='TB_PRODUTO') 
	CREATE TABLE [DBO].[TB_PRODUTO]
	(
		[CD_PRODUTO]		[INT]	IDENTITY(1,1)	NOT NULL,
		[DS_PRODUTO]		[VARCHAR] (50)			NOT NULL,
		[CD_CATEGORIA]		[INT]						NULL,
		[CD_UNIDADE]		[INT]					NOT NULL,
		[CD_BARRA]			[VARCHAR] (48)			NOT NULL,
		[VLR_PRECO]			[MONEY]					NOT NULL,
		[STS_PRODUTO]		[INT]					NOT NULL,
		
		CONSTRAINT [PK_TB_PRODUTO] PRIMARY KEY CLUSTERED ([CD_PRODUTO]) ON [PRIMARY],
		CONSTRAINT [FK_TB_PRODUTO_TB_UNIDADE_MEDIDA] FOREIGN KEY ([CD_UNIDADE]) REFERENCES TB_UNIDADE_MEDIDA ([CD_UNIDADE])

	) ON [PRIMARY]
GO

IF NOT EXISTS(SELECT ID FROM SYSOBJECTS WHERE NAME='TB_FORNECEDOR') 
	CREATE TABLE [DBO].[TB_FORNECEDOR]
	(
		[CD_FORNECEDOR]		[INT]	IDENTITY(1,1)	NOT NULL,
		[RAZAO_SOCIAL]		[VARCHAR] (100)			NOT NULL,
		[NOME_FANTASIA]		[VARCHAR] (100)			NOT NULL,
		[CPF_CNPJ]			[VARCHAR] (18)			NOT NULL,
		[TELEFONE]			[VARCHAR] (20)			NOT NULL,
		[EMAIL]				[VARCHAR] (100)			NOT NULL,
		[STS_PRODUTO]		[INT]						NULL,
		
		CONSTRAINT [PK_FORNECEDOR] PRIMARY KEY CLUSTERED ([CD_FORNECEDOR]) ON [PRIMARY]

	) ON [PRIMARY]
GO